/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mywindow (void)
{
  GtkWidget *mywindow;
  GtkWidget *fixed1;
  GtkWidget *labelNom;
  GtkWidget *entryNom;
  GtkWidget *buttonHello;
  GtkWidget *labelHello;

  mywindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mywindow), _("myfirstwindow"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (mywindow), fixed1);

  labelNom = gtk_label_new (_("Votre nom :"));
  gtk_widget_show (labelNom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNom, 24, 88);
  gtk_widget_set_size_request (labelNom, 81, 32);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom, 112, 88);
  gtk_widget_set_size_request (entryNom, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 8226);

  buttonHello = gtk_button_new_with_mnemonic (_("Say Hello"));
  gtk_widget_show (buttonHello);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonHello, 176, 176);
  gtk_widget_set_size_request (buttonHello, 70, 33);

  labelHello = gtk_label_new (_("Hello"));
  gtk_widget_show (labelHello);
  gtk_fixed_put (GTK_FIXED (fixed1), labelHello, 128, 256);
  gtk_widget_set_size_request (labelHello, 97, 32);

  g_signal_connect ((gpointer) buttonHello, "clicked",
                    G_CALLBACK (on_buttonHello_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mywindow, mywindow, "mywindow");
  GLADE_HOOKUP_OBJECT (mywindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (mywindow, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (mywindow, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (mywindow, buttonHello, "buttonHello");
  GLADE_HOOKUP_OBJECT (mywindow, labelHello, "labelHello");

  return mywindow;
}

