/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_login (void)
{
  GtkWidget *login;
  GtkWidget *fixed1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *password;
  GtkWidget *username;
  GtkWidget *msg;
  GtkWidget *button;

  login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (login), _("login"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (login), fixed1);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 160, 56);
  gtk_widget_set_size_request (entry2, 172, 34);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("hjhjvjhjhj"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 160, 128);
  gtk_widget_set_size_request (entry3, 172, 34);
  gtk_entry_set_text (GTK_ENTRY (entry3), _("kjfh"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  password = gtk_label_new (_("password :\n"));
  gtk_widget_show (password);
  gtk_fixed_put (GTK_FIXED (fixed1), password, 80, 136);
  gtk_widget_set_size_request (password, 73, 17);

  username = gtk_label_new (_("username :\n"));
  gtk_widget_show (username);
  gtk_fixed_put (GTK_FIXED (fixed1), username, 72, 64);
  gtk_widget_set_size_request (username, 88, 16);
  gtk_misc_set_alignment (GTK_MISC (username), 0.49, 0.5);

  msg = gtk_label_new ("");
  gtk_widget_show (msg);
  gtk_fixed_put (GTK_FIXED (fixed1), msg, 40, 200);
  gtk_widget_set_size_request (msg, 41, 17);

  button = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (button);
  gtk_fixed_put (GTK_FIXED (fixed1), button, 216, 224);
  gtk_widget_set_size_request (button, 70, 33);

  g_signal_connect ((gpointer) button, "clicked",
                    G_CALLBACK (on_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login, login, "login");
  GLADE_HOOKUP_OBJECT (login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (login, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (login, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (login, password, "password");
  GLADE_HOOKUP_OBJECT (login, username, "username");
  GLADE_HOOKUP_OBJECT (login, msg, "msg");
  GLADE_HOOKUP_OBJECT (login, button, "button");

  return login;
}

GtkWidget*
create_menu (void)
{
  GtkWidget *menu;
  AtkObject *atko;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *CIN;
  GtkWidget *NOM;
  GtkWidget *PRENOM;
  GtkWidget *ROLE;
  GtkWidget *LABEL;
  GtkWidget *combobox2;
  GtkWidget *ajouter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *modifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *supprimer;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *quitter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *label4;
  GtkWidget *d__con;

  menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menu), _("menu"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (menu), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 272, 72);
  gtk_widget_set_size_request (treeview1, 300, 200);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed3), entry8, 88, 120);
  gtk_widget_set_size_request (entry8, 136, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed3), entry9, 88, 160);
  gtk_widget_set_size_request (entry9, 136, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed3), entry10, 88, 200);
  gtk_widget_set_size_request (entry10, 136, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  CIN = gtk_label_new (_("CIN"));
  gtk_widget_show (CIN);
  gtk_fixed_put (GTK_FIXED (fixed3), CIN, 40, 128);
  gtk_widget_set_size_request (CIN, 41, 17);

  NOM = gtk_label_new (_("NOM"));
  gtk_widget_show (NOM);
  gtk_fixed_put (GTK_FIXED (fixed3), NOM, 40, 168);
  gtk_widget_set_size_request (NOM, 41, 17);

  PRENOM = gtk_label_new (_("PRENOM"));
  gtk_widget_show (PRENOM);
  gtk_fixed_put (GTK_FIXED (fixed3), PRENOM, 16, 208);
  gtk_widget_set_size_request (PRENOM, 72, 24);

  ROLE = gtk_label_new (_("ROLE"));
  gtk_widget_show (ROLE);
  gtk_fixed_put (GTK_FIXED (fixed3), ROLE, 40, 88);
  gtk_widget_set_size_request (ROLE, 41, 17);

  LABEL = gtk_label_new ("");
  gtk_widget_show (LABEL);
  gtk_fixed_put (GTK_FIXED (fixed3), LABEL, 40, 344);
  gtk_widget_set_size_request (LABEL, 152, 40);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox2, 104, 64);
  gtk_widget_set_size_request (combobox2, 97, 51);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("agent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("client"));

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter, 360, 304);
  gtk_widget_set_size_request (ajouter, 96, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), modifier, 256, 304);
  gtk_widget_set_size_request (modifier, 88, 33);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (modifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), supprimer, 472, 304);
  gtk_widget_set_size_request (supprimer, 96, 33);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  quitter = gtk_button_new ();
  gtk_widget_show (quitter);
  gtk_fixed_put (GTK_FIXED (fixed3), quitter, 560, 8);
  gtk_widget_set_size_request (quitter, 24, 24);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (quitter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  label4 = gtk_label_new_with_mnemonic (_("X"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  d__con = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (d__con);
  gtk_fixed_put (GTK_FIXED (fixed3), d__con, 528, 8);
  gtk_widget_set_size_request (d__con, 24, 24);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (ad_activated),
                    NULL);
  g_signal_connect ((gpointer) combobox2, "changed",
                    G_CALLBACK (on_combobox2_changed),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitter, "clicked",
                    G_CALLBACK (quitter_clicked),
                    NULL);
  g_signal_connect ((gpointer) d__con, "clicked",
                    G_CALLBACK (d__con_clicked),
                    NULL);

  atko = gtk_widget_get_accessible (menu);
  atk_object_set_name (atko, _("gestionAgents"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu, menu, "menu");
  GLADE_HOOKUP_OBJECT (menu, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (menu, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (menu, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (menu, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (menu, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (menu, CIN, "CIN");
  GLADE_HOOKUP_OBJECT (menu, NOM, "NOM");
  GLADE_HOOKUP_OBJECT (menu, PRENOM, "PRENOM");
  GLADE_HOOKUP_OBJECT (menu, ROLE, "ROLE");
  GLADE_HOOKUP_OBJECT (menu, LABEL, "LABEL");
  GLADE_HOOKUP_OBJECT (menu, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (menu, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (menu, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (menu, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (menu, image2, "image2");
  GLADE_HOOKUP_OBJECT (menu, label2, "label2");
  GLADE_HOOKUP_OBJECT (menu, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (menu, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (menu, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (menu, image3, "image3");
  GLADE_HOOKUP_OBJECT (menu, label3, "label3");
  GLADE_HOOKUP_OBJECT (menu, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (menu, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (menu, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (menu, image1, "image1");
  GLADE_HOOKUP_OBJECT (menu, label1, "label1");
  GLADE_HOOKUP_OBJECT (menu, quitter, "quitter");
  GLADE_HOOKUP_OBJECT (menu, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (menu, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (menu, label4, "label4");
  GLADE_HOOKUP_OBJECT (menu, d__con, "d__con");

  return menu;
}

